import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { financialReportSummary } from "@/lib/operations.server";
import { createClient } from "@/lib/supabase/server";
import { getLocale, type Locale } from "@/lib/i18n";
import { adminPriceType, adminStatus, getAdminCopy } from "@/lib/admin-copy";
import { AdminChoiceAnalytics } from "@/components/admin-choice-analytics";
import { AdminLiveRefresh } from "@/components/admin-analytics-live-refresh";
import { PrintReportButton } from "@/components/print-report-button";
import { Badge, Button, Card, Input, Select } from "@/components/ui";
import { BuildingIcon, CheckIcon, ShieldCheckIcon, SlidersIcon, StarIcon, WalletIcon } from "@/components/icons";
import { parseCustomerChoiceAnalytics } from "@/lib/customer-choice-analytics";
import { activateNotificationTemplate, approveSupportKnowledgeArticle, archiveSupportKnowledgeArticle, createNotificationTemplate, createSettlement, createSupportKnowledgeArticle, createTreatmentCatalog, createTreatmentVariant, moderateReview, reviewPriceRevision, updateAdminOffer, updateAdminSlot, updateFeatureFlag, updateTreatmentCatalog, updateTreatmentVariant, verifyAndActivate } from "./actions";

export const dynamic = "force-dynamic";

type AdminPageProps = { searchParams: Promise<{ days?: string | string[]; clinic?: string | string[]; start?: string | string[]; end?: string | string[] }> };
type FinancialReport = { clinic_id: string; period_start: string; period_end: string; attended_bookings: number; posted_debit_minor: number; posted_credit_minor: number };
type ProposedSnapshot = { price_type?: string; min_minor?: number | null; max_minor?: number | null; duration_minutes?: number };

function firstValue(value: string | string[] | undefined) {
  return Array.isArray(value) ? value[0] : value;
}

function parseAnalyticsDays(value: string | string[] | undefined): 1 | 7 | 30 {
  const raw = firstValue(value);
  return raw === "1" ? 1 : raw === "30" ? 30 : 7;
}

function qatarDate(daysOffset = 0) {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Qatar", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(Date.now() + daysOffset * 86_400_000));
}

function validDate(value: string | undefined, fallback: string) {
  return value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : fallback;
}

function qatarDateTimeInput(value: string) {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Qatar", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false })
    .formatToParts(new Date(value))
    .reduce<Record<string, string>>((result, part) => ({ ...result, [part.type]: part.value }), {});
  return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;
}

function proposedSummary(snapshot: unknown, locale: Locale) {
  const copy = getAdminCopy(locale);
  if (!snapshot || typeof snapshot !== "object") return copy.priceUnavailable;
  const proposed = snapshot as ProposedSnapshot;
  if (proposed.price_type === "consultation_required") return copy.consultation_required;
  const min = typeof proposed.min_minor === "number" ? `${(proposed.min_minor / 100).toFixed(2)} QAR` : "—";
  const max = typeof proposed.max_minor === "number" ? ` – ${(proposed.max_minor / 100).toFixed(2)} QAR` : "";
  return `${adminPriceType(locale, proposed.price_type ?? "price")}: ${min}${max} · ${proposed.duration_minutes ?? "—"} ${copy.minutes}`;
}

function isFinancialReport(value: unknown): value is FinancialReport {
  if (!value || typeof value !== "object") return false;
  const report = value as Record<string, unknown>;
  return typeof report.clinic_id === "string" && typeof report.attended_bookings === "number" && typeof report.posted_debit_minor === "number" && typeof report.posted_credit_minor === "number";
}

export default async function AdminPage({ searchParams }: AdminPageProps) {
  const [query, cookieStore] = await Promise.all([searchParams, cookies()]);
  const locale = getLocale(cookieStore.get("asnani_locale")?.value);
  const copy = getAdminCopy(locale);
  const days = parseAnalyticsDays(query.days);
  const reportStart = validDate(firstValue(query.start), qatarDate(-29));
  const reportEnd = validDate(firstValue(query.end), qatarDate());
  const supabase = await createClient();
  const { data: claimsData, error } = await supabase.auth.getClaims();
  const meta = (claimsData?.claims?.app_metadata ?? {}) as Record<string, unknown>;
  if (error || !claimsData?.claims?.sub || meta.platform_admin !== true) redirect("/");

  const [
    { data: clinics },
    { data: branches },
    { data: practitioners },
    { data: flags },
    { data: disputes },
    { data: reviews },
    { data: revisions },
    { data: settlements },
    { data: knowledgeArticles },
    { data: notificationTemplates },
    { data: outboxRows },
    { data: treatmentCatalog },
    { data: treatmentVariants },
    { data: adminOffers },
    { data: adminSlots },
    analyticsResult,
  ] = await Promise.all([
    supabase.from("clinics").select("id,display_name,legal_name,status,created_at").order("created_at", { ascending: false }).limit(50),
    supabase.from("branches").select("id,clinic_id,name,status,area").order("created_at", { ascending: false }).limit(100),
    supabase.from("practitioners").select("id,clinic_id,display_name,active,license_ref").limit(100),
    supabase.from("feature_flags").select("key,enabled,config,updated_at").order("key"),
    supabase.from("price_disputes").select("id,branch_id,status,description,created_at").order("created_at", { ascending: false }).limit(20),
    supabase.from("reviews").select("id,rating,review_text,status,created_at").eq("status", "pending").order("created_at", { ascending: false }).limit(20),
    supabase.from("offer_revisions").select("id,offer_id,revision_no,proposed_snapshot,reason,created_at").eq("status", "submitted").order("created_at", { ascending: false }).limit(30),
    supabase.from("settlement_periods").select("id,clinic_id,period_start,period_end,period_kind,status,created_at").order("created_at", { ascending: false }).limit(30),
    supabase.from("support_knowledge_articles").select("id,slug,locale,title,category,audience,status,created_at").order("created_at", { ascending: false }).limit(20),
    supabase.from("notification_templates").select("id,template_key,channel,locale,subject,body,status,version,created_at").order("created_at", { ascending: false }).limit(20),
    supabase.from("notification_outbox").select("id,event_type,channel,locale,status,attempt_count,created_at").order("created_at", { ascending: false }).limit(20),
    supabase.from("treatment_catalog").select("id,code,name_ar,name_en,category,comparison_version,active,updated_at").order("code").limit(100),
    supabase.from("treatment_variants").select("id,catalog_id,variant_key,name_ar,name_en,attributes,active,updated_at").order("variant_key").limit(200),
    supabase.from("branch_service_offers").select("id,branch_id,variant_id,price_type,min_minor,max_minor,duration_minutes,status,updated_at").order("updated_at", { ascending: false }).limit(80),
    supabase.from("availability_slots").select("id,branch_id,variant_id,start_at,end_at,status,updated_at").order("start_at").limit(80),
    supabase.rpc("admin_customer_choice_analytics", { p_days: days }),
  ]);

  const clinicRows = clinics ?? [];
  const branchNameById = new Map((branches ?? []).map((branch) => [branch.id, branch.name]));
  const variantNameById = new Map((treatmentVariants ?? []).map((variant) => [variant.id, locale === "ar" ? variant.name_ar : variant.name_en]));
  const selectedClinicId = clinicRows.some((clinic) => clinic.id === firstValue(query.clinic)) ? firstValue(query.clinic)! : clinicRows[0]?.id;
  const selectedClinic = clinicRows.find((clinic) => clinic.id === selectedClinicId);
  const analytics = analyticsResult.error ? null : parseCustomerChoiceAnalytics(analyticsResult.data);
  const pendingSubjects = [
    ...clinicRows.filter((clinic) => clinic.status === "pending").map((clinic) => ({ type: "clinic", id: clinic.id, label: clinic.display_name })),
    ...(branches ?? []).filter((branch) => branch.status === "pending").map((branch) => ({ type: "branch", id: branch.id, label: branch.name })),
    ...(practitioners ?? []).filter((practitioner) => !practitioner.active).map((practitioner) => ({ type: "practitioner", id: practitioner.id, label: practitioner.display_name })),
  ];

  let report: FinancialReport | null = null;
  let reportUnavailable = false;
  if (selectedClinicId) {
    try {
      const response = await financialReportSummary({ clinicId: selectedClinicId, periodStart: reportStart, periodEnd: reportEnd });
      report = isFinancialReport(response) ? response : null;
    } catch {
      reportUnavailable = true;
    }
  }

  return (
    <main className="mx-auto max-w-7xl px-4 py-9 sm:px-6 sm:py-12">
      <section className="glass-panel rounded-[30px] p-5 sm:p-7">
        <div className="flex flex-wrap items-start justify-between gap-5"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-[#0B5CAD]"><ShieldCheckIcon size={24}/></span><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#084884]">{copy.adminKicker}</p><h1 className="mt-1 text-3xl font-black tracking-tight">{copy.title}</h1><p className="mt-2 max-w-3xl text-sm font-medium leading-6 text-slate-500">{copy.intro}</p></div></div><div className="flex flex-wrap items-center gap-2"><AdminLiveRefresh labels={{ connected: copy.liveConnected, disconnected: copy.liveDisconnected, connecting: copy.liveConnecting, tooltip: copy.liveTooltip }} /><Badge tone="blue">QAR · Asia/Qatar</Badge></div></div>
        <div className="mt-6 grid gap-3 sm:grid-cols-5"><div className="rounded-2xl bg-white/75 p-4 ring-1 ring-slate-200/60"><div className="text-2xl font-black">{pendingSubjects.length}</div><div className="mt-1 text-xs font-bold text-slate-500">{copy.pendingVerification}</div></div><div className="rounded-2xl bg-blue-50/75 p-4 ring-1 ring-blue-100"><div className="text-2xl font-black text-[#084884]">{revisions?.length ?? 0}</div><div className="mt-1 text-xs font-bold text-slate-500">{copy.pendingPriceRevisions}</div></div><div className="rounded-2xl bg-white/75 p-4 ring-1 ring-slate-200/60"><div className="text-2xl font-black">{flags?.length ?? 0}</div><div className="mt-1 text-xs font-bold text-slate-500">{copy.featureFlags}</div></div><div className="rounded-2xl bg-amber-50/75 p-4 ring-1 ring-amber-100"><div className="text-2xl font-black text-amber-800">{reviews?.length ?? 0}</div><div className="mt-1 text-xs font-bold text-slate-500">{copy.pendingReviews}</div></div><div className="rounded-2xl bg-red-50/75 p-4 ring-1 ring-red-100"><div className="text-2xl font-black text-red-700">{disputes?.length ?? 0}</div><div className="mt-1 text-xs font-bold text-slate-500">{copy.recentPriceDisputes}</div></div></div>
      </section>

      {analytics ? <AdminChoiceAnalytics analytics={analytics} days={days} locale={locale} /> : <Card className="mt-7 border border-red-200 bg-red-50/70 p-5 text-red-800"><div className="font-black">{copy.analyticsUnavailable}</div><p className="mt-2 text-sm font-medium">{copy.analyticsUnavailableCopy}</p></Card>}

      <section className="mt-7 grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><BuildingIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.pendingItems}</h2></div><div className="mt-4 space-y-3">{pendingSubjects.length ? pendingSubjects.map((subject) => <form key={`${subject.type}-${subject.id}`} action={verifyAndActivate} className="rounded-[22px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="subject_type" value={subject.type}/><input type="hidden" name="subject_id" value={subject.id}/><div className="flex items-center justify-between gap-3"><div><div className="font-black">{subject.label}</div><div className="mt-1 text-xs font-bold text-slate-500">{subject.type === "clinic" ? copy.sourceClinic : subject.type === "branch" ? copy.sourceBranch : copy.sourcePractitioner}</div></div><Badge tone="amber">{copy.pending}</Badge></div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input name="source" required placeholder={copy.verifySource}/><Input name="identifier" placeholder={copy.licenceReference}/><Button className="gap-2"><CheckIcon size={17}/>{copy.verifyActivate}</Button></div></form>) : <div className="rounded-2xl bg-emerald-50 p-5 text-sm font-bold text-emerald-800">{copy.noPendingItems}</div>}</div></Card>
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><SlidersIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.featureFlags}</h2></div><div className="mt-4 space-y-3">{flags?.map((flag) => <form action={updateFeatureFlag} key={flag.key} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="key" value={flag.key}/><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate font-black">{flag.key}</div><div className="mt-1 text-xs font-bold text-slate-500">{flag.enabled ? copy.enabled : copy.disabled}</div></div><Badge tone={flag.enabled ? "green" : "slate"}>{flag.enabled ? copy.enabled : copy.disabled}</Badge></div><div className="mt-3 grid gap-2"><Select name="enabled" defaultValue={String(flag.enabled)}><option value="false">{copy.disabled}</option><option value="true">{copy.enabled}</option></Select><textarea name="config_json" defaultValue={JSON.stringify(flag.config ?? {})} className="min-h-20 rounded-2xl border border-slate-200 bg-white px-3 py-2 font-mono text-xs outline-none ring-[#0B5CAD]/20 transition focus:ring-4" aria-label={copy.configJson.replace("{key}", flag.key)}/><Button>{copy.savePublishConfig}</Button></div></form>)}</div></Card>
      </section>

      <section className="mt-6 grid gap-6 lg:grid-cols-2">
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><WalletIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.priceReview}</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.priceReviewCopy}</p><div className="mt-4 space-y-3">{revisions?.length ? revisions.map((revision) => <form key={revision.id} action={reviewPriceRevision} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="revision_id" value={revision.id}/><div className="flex items-start justify-between gap-3"><div><div className="font-black">{copy.offer} {revision.offer_id.slice(0, 8)} · v{revision.revision_no}</div><div className="mt-1 text-xs font-bold text-slate-600">{proposedSummary(revision.proposed_snapshot, locale)}</div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.clinicReason}: {revision.reason}</p></div><Badge tone="amber">{copy.submitted}</Badge></div><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><Input name="reason" minLength={3} placeholder={copy.rejectReason}/><button type="submit" name="decision" value="approve" className="rounded-full bg-emerald-600 px-4 text-sm font-black text-white transition hover:bg-emerald-700">{copy.approve}</button><button type="submit" name="decision" value="reject" className="rounded-full bg-red-600 px-4 text-sm font-black text-white transition hover:bg-red-700">{copy.reject}</button></div></form>) : <p className="rounded-2xl bg-emerald-50 p-5 text-sm font-bold text-emerald-800">{copy.noPriceRevisions}</p>}</div></Card>
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><WalletIcon size={19} className="text-emerald-600"/><h2 className="font-black">{copy.createSettlement}</h2></div><form action={createSettlement} className="mt-4 grid gap-3"><Select name="clinic_id" required>{clinicRows.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.display_name}</option>)}</Select><div className="grid grid-cols-2 gap-2"><label className="grid gap-1 text-xs font-bold text-slate-600">{copy.start}<Input name="period_start" type="date" defaultValue={reportStart} required/></label><label className="grid gap-1 text-xs font-bold text-slate-600">{copy.end}<Input name="period_end" type="date" defaultValue={reportEnd} required/></label></div><Select name="period_kind" defaultValue="monthly"><option value="weekly">{copy.weekly}</option><option value="monthly">{copy.monthly}</option><option value="annual">{copy.annual}</option><option value="manual">{copy.manual}</option></Select><Input name="notes" maxLength={1000} placeholder={copy.optionalNotes}/><Button>{copy.createOpenSettlement}</Button></form><div className="mt-4 space-y-2 text-xs">{settlements?.length ? settlements.slice(0, 6).map((settlement) => <div key={settlement.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><span>{settlement.period_start} — {settlement.period_end}</span><Badge tone={settlement.status === "closed" ? "green" : "slate"}>{adminStatus(locale, settlement.status)}</Badge></div>) : <span className="text-slate-500">{copy.noSettlements}</span>}</div></Card>
      </section>

      <section id="catalog-governance" className="mt-6 grid gap-6 lg:grid-cols-2">
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><SlidersIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.catalogTitle}</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.catalogCopy}</p><form action={createTreatmentCatalog} className="mt-4 grid gap-2 rounded-2xl bg-blue-50/50 p-4 ring-1 ring-blue-100"><div className="grid gap-2 sm:grid-cols-2"><Input name="code" required pattern="[a-z0-9_]{2,80}" placeholder="code_en"/><Input name="category" required pattern="[a-z0-9_-]{2,80}" placeholder="category_en"/></div><div className="grid gap-2 sm:grid-cols-2"><Input name="name_ar" required maxLength={160} placeholder={copy.arabicTreatmentName}/><Input name="name_en" required maxLength={160} placeholder={copy.englishTreatmentName}/></div><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Input name="comparison_version" type="number" min="1" max="999" defaultValue="1" required/><input type="hidden" name="active" value="true"/><Button>{copy.addTreatment}</Button></div></form><div className="mt-4 space-y-3">{treatmentCatalog?.length ? treatmentCatalog.map((item) => <form key={item.id} action={updateTreatmentCatalog} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="id" value={item.id}/><div className="grid gap-2 sm:grid-cols-2"><Input name="code" required pattern="[a-z0-9_]{2,80}" defaultValue={item.code}/><Input name="category" required pattern="[a-z0-9_-]{2,80}" defaultValue={item.category}/><Input name="name_ar" required maxLength={160} defaultValue={item.name_ar}/><Input name="name_en" required maxLength={160} defaultValue={item.name_en}/><Input name="comparison_version" type="number" min="1" max="999" defaultValue={item.comparison_version}/><Select name="active" defaultValue={String(item.active)}><option value="true">{copy.visibleAvailable}</option><option value="false">{copy.hiddenUnavailable}</option></Select></div><div className="mt-3 flex items-center justify-between gap-3"><Badge tone={item.active ? "green" : "slate"}>{item.active ? copy.visible : copy.hidden}</Badge><Button className="min-h-9 px-4 py-1 text-xs">{copy.saveTreatment}</Button></div></form>) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">{copy.noCatalogItems}</p>}</div></Card>
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><ShieldCheckIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.variantsTitle}</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.variantsCopy}</p><form action={createTreatmentVariant} className="mt-4 grid gap-2 rounded-2xl bg-blue-50/50 p-4 ring-1 ring-blue-100"><Select name="catalog_id" required>{treatmentCatalog?.map((item) => <option key={item.id} value={item.id}>{locale === "ar" ? item.name_ar : item.name_en} · {item.code}</option>)}</Select><div className="grid gap-2 sm:grid-cols-2"><Input name="variant_key" required pattern="[a-z0-9_]{2,100}" placeholder="variant_key"/><Input name="name_ar" required maxLength={160} placeholder={copy.arabicVariantName}/><Input name="name_en" required maxLength={160} placeholder={copy.englishVariantName}/><input type="hidden" name="active" value="true"/></div><textarea name="attributes_json" defaultValue="{}" className="min-h-16 rounded-2xl border border-slate-200 bg-white px-3 py-2 font-mono text-xs outline-none ring-[#0B5CAD]/20 transition focus:ring-4" aria-label={copy.variantAttributes}/><Button>{copy.addVariant}</Button></form><div className="mt-4 space-y-3">{treatmentVariants?.length ? treatmentVariants.map((item) => <form key={item.id} action={updateTreatmentVariant} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="id" value={item.id}/><Select name="catalog_id" defaultValue={item.catalog_id}>{treatmentCatalog?.map((catalog) => <option key={catalog.id} value={catalog.id}>{locale === "ar" ? catalog.name_ar : catalog.name_en} · {catalog.code}</option>)}</Select><div className="mt-2 grid gap-2 sm:grid-cols-2"><Input name="variant_key" required pattern="[a-z0-9_]{2,100}" defaultValue={item.variant_key}/><Input name="name_ar" required maxLength={160} defaultValue={item.name_ar}/><Input name="name_en" required maxLength={160} defaultValue={item.name_en}/><Select name="active" defaultValue={String(item.active)}><option value="true">{copy.visibleAvailable}</option><option value="false">{copy.hiddenUnavailable}</option></Select></div><textarea name="attributes_json" defaultValue={JSON.stringify(item.attributes ?? {})} className="mt-2 min-h-16 w-full rounded-2xl border border-slate-200 bg-white px-3 py-2 font-mono text-xs outline-none ring-[#0B5CAD]/20 transition focus:ring-4" aria-label={copy.variantAttributes}/><div className="mt-3 flex items-center justify-between gap-3"><Badge tone={item.active ? "green" : "slate"}>{item.active ? copy.visible : copy.hidden}</Badge><Button className="min-h-9 px-4 py-1 text-xs">{copy.saveVariant}</Button></div></form>) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">{copy.noVariants}</p>}</div></Card>
      </section>

      <section id="admin-offer-slot-control" className="mt-6 grid gap-6 lg:grid-cols-2">
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><WalletIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.offerControl}</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.offerControlCopy}</p><div className="mt-4 space-y-3">{adminOffers?.length ? adminOffers.map((offer) => <form key={offer.id} action={updateAdminOffer} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="id" value={offer.id}/><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="font-black">{variantNameById.get(offer.variant_id) ?? offer.variant_id.slice(0, 8)}</div><div className="mt-1 text-xs font-bold text-slate-500">{branchNameById.get(offer.branch_id) ?? offer.branch_id.slice(0, 8)}</div></div><Badge tone={offer.status === "active" ? "green" : offer.status === "suspended" || offer.status === "archived" ? "slate" : "amber"}>{adminStatus(locale, offer.status)}</Badge></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Select name="price_type" defaultValue={offer.price_type}><option value="fixed">{copy.fixed}</option><option value="from">{copy.from}</option><option value="range">{copy.range}</option><option value="package">{copy.package}</option><option value="consultation_required">{copy.consultation_required}</option></Select><Select name="status" defaultValue={offer.status}><option value="draft">{copy.draft}</option><option value="active">{copy.active}</option><option value="needs_review">{copy.needs_review}</option><option value="stale">{copy.stale}</option><option value="suspended">{copy.suspended}</option><option value="archived">{copy.archived}</option></Select><Input name="min_qar" type="number" min="0" step="0.01" defaultValue={offer.min_minor === null ? "" : offer.min_minor / 100} placeholder={copy.minQar}/><Input name="max_qar" type="number" min="0" step="0.01" defaultValue={offer.max_minor === null ? "" : offer.max_minor / 100} placeholder={copy.maxQar}/><Input name="duration_minutes" type="number" min="5" max="480" defaultValue={offer.duration_minutes}/><Button className="sm:col-span-2">{copy.saveOfferPublish}</Button></div></form>) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">{copy.noControllableOffers}</p>}</div></Card>
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><BuildingIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.slotControl}</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.slotControlCopy}</p><div className="mt-4 space-y-3">{adminSlots?.length ? adminSlots.map((slot) => <form key={slot.id} action={updateAdminSlot} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="id" value={slot.id}/><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="font-black">{variantNameById.get(slot.variant_id) ?? slot.variant_id.slice(0, 8)}</div><div className="mt-1 text-xs font-bold text-slate-500">{branchNameById.get(slot.branch_id) ?? slot.branch_id.slice(0, 8)}</div></div><Badge tone={slot.status === "published" ? "green" : slot.status === "cancelled" || slot.status === "consumed" ? "slate" : "amber"}>{adminStatus(locale, slot.status)}</Badge></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold text-slate-600">{copy.start}<Input name="start_at" type="datetime-local" defaultValue={qatarDateTimeInput(slot.start_at)} required/></label><label className="grid gap-1 text-xs font-bold text-slate-600">{copy.end}<Input name="end_at" type="datetime-local" defaultValue={qatarDateTimeInput(slot.end_at)} required/></label><Select name="status" defaultValue={slot.status}><option value="draft">{copy.draft}</option><option value="published">{copy.published}</option><option value="held">{copy.held}</option><option value="consumed">{copy.consumed}</option><option value="expired">{copy.expired}</option><option value="cancelled">{copy.cancelled}</option></Select><Button>{copy.saveSlotPublish}</Button></div></form>) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">{copy.noControllableSlots}</p>}</div></Card>
      </section>

      <section id="financial-report" className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
        <Card className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><WalletIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.financeTitle}</h2></div><div className="flex flex-wrap gap-2"><PrintReportButton label={copy.print} />{selectedClinicId && <a href={`/api/admin/reports/csv?clinic=${encodeURIComponent(selectedClinicId)}&start=${encodeURIComponent(reportStart)}&end=${encodeURIComponent(reportEnd)}`} className="inline-flex min-h-10 items-center justify-center rounded-full border border-slate-300 bg-white px-4 text-sm font-black text-slate-800 transition hover:bg-slate-50">CSV</a>}</div></div><form method="get" className="mt-4 grid gap-3 sm:grid-cols-4"><Select name="clinic" defaultValue={selectedClinicId}>{clinicRows.map((clinic) => <option key={clinic.id} value={clinic.id}>{clinic.display_name}</option>)}</Select><Input name="start" type="date" defaultValue={reportStart}/><Input name="end" type="date" defaultValue={reportEnd}/><Button>{copy.refreshReport}</Button></form>{report ? <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-2xl font-black text-[#084884]">{report.attended_bookings}</div><div className="mt-1 text-xs font-bold text-slate-600">{copy.attendedPatients}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-2xl font-black">{(report.posted_debit_minor / 100).toFixed(2)}</div><div className="mt-1 text-xs font-bold text-slate-600">{copy.totalDebit}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-2xl font-black text-emerald-700">{(report.posted_credit_minor / 100).toFixed(2)}</div><div className="mt-1 text-xs font-bold text-slate-600">{copy.totalCredit}</div></div></div> : <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-800">{reportUnavailable ? copy.reportUnavailable : copy.noClinicReport}</p>}<p className="mt-4 text-xs leading-5 text-slate-500">{copy.reportScope}: {reportStart} — {reportEnd} · {selectedClinic?.display_name ?? "—"}. {copy.reportScopeCopy}</p></Card>
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><StarIcon size={19} className="text-amber-500"/><h2 className="font-black">{copy.reviewsTitle}</h2></div><div className="mt-4 space-y-3">{reviews?.length ? reviews.map((review) => <form key={review.id} action={moderateReview} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><input type="hidden" name="id" value={review.id}/><div className="font-bold"><span className="inline-flex items-center gap-1"><StarIcon size={14} className="text-amber-500"/>{review.rating}/5</span> · {review.review_text || copy.noReviewText}</div><div className="mt-3 flex gap-2"><Select name="status" defaultValue="published"><option value="published">{copy.published}</option><option value="hidden">{copy.hidden}</option><option value="removed">{copy.removed}</option></Select><Button>{copy.approve}</Button></div></form>) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">{copy.noPendingReviews}</p>}</div><div className="mt-6 border-t border-slate-200 pt-6"><div className="flex items-center gap-2"><WalletIcon size={19} className="text-red-500"/><h2 className="font-black">{copy.disputesTitle}</h2></div><div className="mt-4 space-y-2">{disputes?.length ? disputes.map((dispute) => <div key={dispute.id} className="rounded-[20px] bg-slate-50/80 p-4 ring-1 ring-slate-200/60"><div className="text-sm font-bold">{dispute.description}</div><div className="mt-2"><Badge tone={dispute.status === "resolved" ? "green" : "amber"}>{adminStatus(locale, dispute.status)}</Badge></div></div>) : <p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">{copy.noDisputes}</p>}</div></div></Card>
      </section>

      <section className="mt-6 grid gap-6 lg:grid-cols-2">
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><ShieldCheckIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.knowledgeTitle}</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.knowledgeCopy}</p><form action={createSupportKnowledgeArticle} className="mt-4 grid gap-3"><div className="grid grid-cols-2 gap-2"><Input name="slug" required pattern="[a-z0-9-]{3,100}" placeholder="slug-en-lowercase"/><Select name="locale" defaultValue="ar"><option value="ar">{copy.arabic}</option><option value="en">{copy.english}</option></Select></div><div className="grid grid-cols-2 gap-2"><Select name="category" defaultValue="booking"><option value="booking">{copy.booking}</option><option value="pricing">{copy.pricing}</option><option value="availability">{copy.availability}</option><option value="account">{copy.account}</option><option value="clinic">{copy.clinicAudience}</option><option value="policy">{copy.policy}</option><option value="safety">{copy.safety}</option></Select><Select name="audience" defaultValue="public"><option value="public">{copy.publicAudience}</option><option value="clinic">{copy.clinicAudience}</option><option value="admin">{copy.adminAudience}</option></Select></div><Input name="title" required maxLength={200} placeholder={copy.articleTitle}/><textarea name="body_markdown" required minLength={10} maxLength={20000} className="min-h-28 rounded-2xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none ring-[#0B5CAD]/20 transition focus:ring-4" placeholder={copy.articleBody}/><Button>{copy.saveKnowledgeDraft}</Button></form><div className="mt-5 space-y-2">{knowledgeArticles?.length ? knowledgeArticles.map((article) => <div key={article.id} className="rounded-2xl bg-slate-50 p-3 text-sm ring-1 ring-slate-200/60"><div className="flex items-center justify-between gap-3"><div><div className="font-black">{article.title}</div><div className="mt-1 text-xs text-slate-500">{article.locale === "ar" ? copy.arabic : copy.english} · {copy[article.category] ?? article.category} · {article.audience === "public" ? copy.publicAudience : article.audience === "clinic" ? copy.clinicAudience : copy.adminAudience}</div></div><Badge tone={article.status === "approved" ? "green" : article.status === "archived" ? "slate" : "amber"}>{adminStatus(locale, article.status)}</Badge></div><div className="mt-2 flex flex-wrap gap-2">{article.status === "draft" && <form action={approveSupportKnowledgeArticle}><input type="hidden" name="id" value={article.id}/><Button className="min-h-8 px-3 py-1 text-xs">{copy.approveKnowledge}</Button></form>}{article.status !== "archived" && <form action={archiveSupportKnowledgeArticle}><input type="hidden" name="id" value={article.id}/><Button className="min-h-8 bg-slate-700 px-3 py-1 text-xs hover:bg-slate-800">{copy.archiveArticle}</Button></form>}</div></div>) : <p className="text-sm text-slate-500">{copy.noKnowledge}</p>}</div></Card>
        <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><WalletIcon size={19} className="text-[#0B5CAD]"/><h2 className="font-black">{copy.notificationsTitle}</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">{copy.notificationsCopy}</p><form action={createNotificationTemplate} className="mt-4 grid gap-3"><div className="grid grid-cols-3 gap-2"><Input name="template_key" required pattern="[a-z0-9_.-]{3,80}" placeholder="booking_confirmed"/><Select name="channel" defaultValue="push"><option value="push">{copy.push}</option><option value="email">{copy.email}</option><option value="sms">{copy.sms}</option></Select><Select name="locale" defaultValue="ar"><option value="ar">{copy.arabic}</option><option value="en">{copy.english}</option></Select></div><Input name="subject" maxLength={200} placeholder={copy.emailSubject}/><textarea name="body" required maxLength={4000} className="min-h-24 rounded-2xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none ring-[#0B5CAD]/20 transition focus:ring-4" placeholder={copy.templateBody}/><Button>{copy.saveTemplateDraft}</Button></form><div className="mt-5 space-y-2">{notificationTemplates?.length ? notificationTemplates.map((template) => <div key={template.id} className="rounded-2xl bg-slate-50 p-3 text-sm ring-1 ring-slate-200/60"><div className="flex items-center justify-between gap-3"><div><div className="font-black">{template.template_key} · v{template.version}</div><div className="mt-1 text-xs text-slate-500">{copy[template.channel] ?? template.channel} · {template.locale === "ar" ? copy.arabic : copy.english}</div></div><Badge tone={template.status === "active" ? "green" : "amber"}>{adminStatus(locale, template.status)}</Badge></div>{template.status === "draft" && <form action={activateNotificationTemplate} className="mt-2"><input type="hidden" name="id" value={template.id}/><Button className="min-h-8 px-3 py-1 text-xs">{copy.activateTemplate}</Button></form>}</div>) : <p className="text-sm text-slate-500">{copy.noTemplates}</p>}</div><div className="mt-5 border-t border-slate-200 pt-4"><div className="text-sm font-black">{copy.outboxTitle}</div><div className="mt-2 space-y-2">{outboxRows?.length ? outboxRows.slice(0, 6).map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-xs"><span>{item.event_type} · {copy[item.channel] ?? item.channel} · {item.locale === "ar" ? copy.arabic : copy.english}</span><Badge tone={item.status === "sent" ? "green" : item.status === "failed" ? "red" : "amber"}>{adminStatus(locale, item.status)} · {item.attempt_count}</Badge></div>) : <span className="text-xs text-slate-500">{copy.noOutbox}</span>}</div></div></Card>
      </section>
    </main>
  );
}
