-- Remote migration history marker: 20260914010348.
-- The waitlist schema is consolidated and reproducible in the later canonical migration.
-- This file intentionally contains no DDL; Supabase tracks migration history by timestamp.